import { createContext, useContext, useState, type ReactNode } from 'react';

type Lang = 'en' | 'uk';

const translations: Record<Lang, Record<string, string>> = {
  en: {
    title: 'Elementary Learning Hub',
    subtitle: 'Choose your subject to start learning!',
    math: 'Math',
    english: 'English',
    ukrainian: 'Ukrainian',
    statistics: 'Statistics',
    logout: 'Logout',
    profile: 'Profile',
    backHome: 'Back to Home',
    welcome: 'Welcome',
    createAccount: 'Create an account',
    signUp: 'Sign Up',
    login: 'Login',
    haveAccount: 'Already have an account?',
    adminLogin: 'Admin Login',
    avatarShop: 'Avatar Shop',
    achievements: 'Achievements & Badges',
    locked: 'Locked',
    points: 'Points',
    streak: 'Day Streak',
    grade: 'Grade',
    installApp: 'Install App',
    installHint: 'Add to your home screen for the full app experience!',
    myAccount: 'My Account',
    welcomeTitle: 'Welcome!',
    welcomeSub: 'Choose how you want to continue',
    chooseSection: 'Choose a section, then a subtopic',
    chooseTopic: 'Choose a topic to start learning! 🚀',
    tabProblems: 'Problems',
    problemsDesc: 'Practice with interactive problems and earn points.',
    examplesIntro: 'See step-by-step examples of how to solve similar questions.',
    videoSingular: 'video',
    videosPlural: 'videos',
    exerciseSingular: 'exercise',
    exercisesPlural: 'exercises',
    section: 'Section',
    topic: 'Topic',
    tabVideo: 'Video',
    tabLecture: 'Lecture',
    tabExamples: 'Examples',
    tabAssignments: 'Assignments',
    lectureEmpty: 'No lecture text yet.',
    examplesEmpty: 'No examples yet.',
    assignmentEmpty: 'No assignment linked yet.',
    assignmentDeleted: 'This assignment was deleted. Ask your teacher to link a new one.',
    startAssignment: 'Start assignment',
    open: 'Open',
    adminPanel: 'Admin Panel',
    edit: 'edit',
    addNewItem: 'add a new item',
    addTopicHint: '+ add a new topic (use curriculum seed or API)',
    addSubtopicHint: '+ add a new subtopic',
    assignmentBuilder: 'Assignment Builder',
    addVideo: 'Add Video',
    addLecture: 'Add lecture',
    addExamples: 'Add examples',
    addTask: 'Add task',
    youtubeUrl: 'YouTube link',
    uploadFromComputer: 'Upload from your computer',
    uploadVideo: 'Upload video',
    saveYoutube: 'Save YouTube link',
    currentLocalVideo: 'Local file',
    chooseVideoFile: 'Choose a video file first',
    uploading: 'Uploading...',
    videoUploaded: 'Video uploaded!',
    saved: 'Saved!',
    save: 'Save',
    subtopicName: 'Subtopic name',
    videoTitle: 'Video title',
    videoDescription: 'Video description',
    lectureTitle: 'Lecture title',
    lectureParagraphs: 'Paragraphs (one per line)',
    exampleTitle: 'Title',
    exampleBody: 'Description',
    addExample: 'Add example',
    remove: 'Remove',
    linkAssignment: 'Link assignment',
    createAssignment: 'Create new assignment',
    assignments: 'Assignments',
    assignmentsDesc: 'Practice with interactive exercises',
    videoExplanation: 'Video Explanation',
    textLecture: 'Text Lecture',
    backToTopic: 'Back to Topic',
    videoPlaceholder: 'No video uploaded yet. Check the lecture or assignment!',
    guestMessage: 'Log in to save your progress and customize your avatar.',
    appInstalled: 'App is installed',
    iosInstallHint: 'Tap Share, then "Add to Home Screen" to install.',
    desktopInstallHint: 'Use Chrome menu (⋮) → "Install app" or "Add to Home screen".',
    installNeedsHttps: 'Install works on the live website (HTTPS). Use the deployed link.',
    subtopics: 'Subtopics',
    videoComingSoon: 'Video coming soon — admin can upload',
  },
  uk: {
    title: 'Початковий Навчальний Центр',
    subtitle: 'Оберіть предмет, щоб почати навчання!',
    math: 'Математика',
    english: 'Англійська',
    ukrainian: 'Українська',
    statistics: 'Статистика',
    logout: 'Вийти',
    profile: 'Профіль',
    backHome: 'На головну',
    welcome: 'Вітаємо',
    createAccount: 'Створити акаунт',
    signUp: 'Зареєструватися',
    login: 'Увійти',
    haveAccount: 'Вже є акаунт?',
    adminLogin: 'Вхід адміна',
    avatarShop: 'Магазин аватара',
    achievements: 'Досягнення та значки',
    locked: 'Заблоковано',
    points: 'Бали',
    streak: 'Серія днів',
    grade: 'Клас',
    installApp: 'Встановити',
    installHint: 'Додайте на головний екран для повного досвіду!',
    myAccount: 'Мій акаунт',
    welcomeTitle: 'Вітаємо!',
    welcomeSub: 'Оберіть, як продовжити',
    chooseSection: 'Оберіть розділ, потім тему',
    chooseTopic: 'Оберіть тему, щоб почати навчання! 🚀',
    tabProblems: 'Завдання',
    problemsDesc: 'Практикуйте інтерактивні завдання та заробляйте бали.',
    examplesIntro: 'Перегляньте приклади розв’язування подібних задач.',
    videoSingular: 'відео',
    videosPlural: 'відео',
    exerciseSingular: 'вправа',
    exercisesPlural: 'вправи',
    section: 'Розділ',
    topic: 'Тема',
    tabVideo: 'Відео',
    tabLecture: 'Лекція',
    tabExamples: 'Приклади',
    tabAssignments: 'Завдання',
    lectureEmpty: 'Текст лекції ще не додано.',
    examplesEmpty: 'Прикладів ще немає.',
    assignmentEmpty: 'Завдання ще не прив’язано.',
    assignmentDeleted: 'Це завдання видалено. Попросіть вчителя прив’язати нове.',
    startAssignment: 'Почати завдання',
    open: 'Відкрити',
    adminPanel: 'Панель адміна',
    edit: 'редагувати',
    addNewItem: 'додати новий предмет',
    addTopicHint: '+ додати нову тему',
    addSubtopicHint: '+ додати нову підтему',
    assignmentBuilder: 'Конструктор завдань',
    addVideo: 'Додати відео',
    addLecture: 'Додати лекцію',
    addExamples: 'Додати приклади',
    addTask: 'Додати завдання',
    youtubeUrl: 'Посилання YouTube',
    uploadFromComputer: 'Завантажити з комп’ютера',
    uploadVideo: 'Завантажити відео',
    saveYoutube: 'Зберегти YouTube',
    currentLocalVideo: 'Локальний файл',
    chooseVideoFile: 'Спочатку оберіть файл',
    uploading: 'Завантаження...',
    videoUploaded: 'Відео завантажено!',
    saved: 'Збережено!',
    save: 'Зберегти',
    subtopicName: 'Назва підтеми',
    videoTitle: 'Назва відео',
    videoDescription: 'Опис відео',
    lectureTitle: 'Назва лекції',
    lectureParagraphs: 'Абзаци (по одному в рядку)',
    exampleTitle: 'Заголовок',
    exampleBody: 'Опис',
    addExample: 'Додати приклад',
    remove: 'Видалити',
    linkAssignment: 'Прив’язати завдання',
    createAssignment: 'Створити завдання',
    assignments: 'Завдання',
    assignmentsDesc: 'Практикуйтеся з інтерактивними вправами',
    videoExplanation: 'Відео пояснення',
    textLecture: 'Текстова лекція',
    backToTopic: 'Назад до теми',
    videoPlaceholder: 'Відеоуроки незабаром — прочитайте лекцію та виконайте завдання!',
    guestMessage: 'Увійдіть, щоб зберігати прогрес і налаштувати аватар.',
    appInstalled: 'Додаток встановлено',
    iosInstallHint: 'Натисніть «Поділитися», потім «На Початковий екран».',
    desktopInstallHint: 'Меню Chrome (⋮) → «Встановити додаток».',
    installNeedsHttps: 'Встановлення працює на опублікованому сайті (HTTPS).',
    subtopics: 'Підтеми',
    videoComingSoon: 'Відео незабаром — адмін може завантажити',
  },
};

const LanguageContext = createContext<{
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
} | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');
  const t = (key: string) => translations[lang][key] || translations.en[key] || key;
  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
