export const SHOP_ITEMS = [
  { id: 'hair-blonde', category: 'hair', label: 'Blonde Hair', cost: 25, value: 'blonde' },
  { id: 'hair-black', category: 'hair', label: 'Black Hair', cost: 25, value: 'black' },
  { id: 'hair-red', category: 'hair', label: 'Red Hair', cost: 30, value: 'red' },
  { id: 'hair-curly', category: 'hair', label: 'Curly Style', cost: 40, value: 'curly' },
  { id: 'hair-long', category: 'hair', label: 'Long Hair', cost: 45, value: 'long' },
  { id: 'skin-light', category: 'skin', label: 'Light Skin', cost: 0, value: '#FFE0BD' },
  { id: 'skin-medium', category: 'skin', label: 'Medium Skin', cost: 0, value: '#F5D0A9' },
  { id: 'skin-tan', category: 'skin', label: 'Tan Skin', cost: 15, value: '#D4A574' },
  { id: 'skin-dark', category: 'skin', label: 'Dark Skin', cost: 15, value: '#8D5524' },
  { id: 'top-red', category: 'top', label: 'Red Shirt', cost: 35, value: 'red' },
  { id: 'top-blue', category: 'top', label: 'Blue Shirt', cost: 35, value: 'blue' },
  { id: 'top-green', category: 'top', label: 'Green Shirt', cost: 35, value: 'green' },
  { id: 'top-purple', category: 'top', label: 'Purple Hoodie', cost: 50, value: 'purple' },
  { id: 'bottom-jeans', category: 'bottom', label: 'Jeans', cost: 30, value: 'jeans' },
  { id: 'bottom-shorts', category: 'bottom', label: 'Shorts', cost: 25, value: 'shorts' },
  { id: 'bottom-skirt', category: 'bottom', label: 'Skirt', cost: 35, value: 'skirt' },
  { id: 'shoes-sneakers', category: 'shoes', label: 'Sneakers', cost: 30, value: 'sneakers' },
  { id: 'shoes-boots', category: 'shoes', label: 'Boots', cost: 40, value: 'boots' },
  { id: 'shoes-sandals', category: 'shoes', label: 'Sandals', cost: 25, value: 'sandals' },
  { id: 'acc-glasses', category: 'accessory', label: 'Glasses', cost: 45, value: 'glasses' },
  { id: 'acc-hat', category: 'accessory', label: 'Cap', cost: 40, value: 'hat' },
  { id: 'acc-bow', category: 'accessory', label: 'Bow', cost: 35, value: 'bow' },
  { id: 'acc-backpack', category: 'accessory', label: 'Backpack', cost: 55, value: 'backpack' },
];

export const ACHIEVEMENTS = [
  { id: 'task-master', title: 'Task Master', description: 'Complete 10 tasks', check: (s) => s.completedCount >= 10 },
  { id: 'course-hero', title: 'Course Hero', description: 'Complete a full course', check: (s) => s.subjectsCompleted >= 1 },
  { id: 'dedication', title: 'Dedication', description: '20 day login streak', check: (s) => s.streak >= 20 },
  { id: 'star-collector', title: 'Star Collector', description: 'Earn 50 stars total', check: (s) => s.stars >= 50 },
  { id: 'points-master', title: 'Points Master', description: 'Earn 500 points', check: (s) => s.points >= 500 },
  { id: 'early-bird', title: 'Early Bird', description: 'Log in 7 days in a row', check: (s) => s.streak >= 7 },
];
